# Site settings
title: Jonas Degrave
header-img: img/home-bg.jpg
email: Jonas.Degrave@UGent.be
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "https://317070.github.io"
twitter_username: 317070
github_username: 317070
facebook_username: jonas.debraeve

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

analytics :
  provider : google
  google : 
    tracking_id : 'UA-60860556-1'
  getclicky :
    site_id : 
